gui:
  language: "en"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
      # Customize the color highlights of the branch
  branchColors:
    "docs": "#11aaff"
    "dev*": "#ebad6c"
    "main": "#af92fc"
    "master": "#af92fc"
  showDivergenceFromBaseBranch: onlyArrow
  filterMode: fuzzy
disableStartupPopups: true
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --syntax-theme="Catppuccin Mocha"
os:
  editPreset: "nvim"
