gui:
  language: "en"
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: onlyArrow
  filterMode: fuzzy
  showFileIcons: true
  sidePanelWidth: 0.3
  showBottomLine: false
  showCommandLog: false
  commitLength:
    show: true
  branchColors:
    "docs": "#11aaff"
    "dev*": "#ebad6c"
    "main": "#af92fc"
    "master": "#af92fc"
disableStartupPopups: true
git:
  parseEmoji: true
  autoFetch: true
  autoRefresh: true
  # skipHookPrefix: "WIP"
  diffRenderers:
    - colorArg: always
      command: delta --paging=never --syntax-theme="Catppuccin Mocha"
  # log 显示 graph
  log:
    showGraph: always
    showWholeGraph: false
os:
  editPreset: "nvim"
promptToReturnFromSubprocess: false
customCommands:
  - key: "R"
    context: "commits"
    command: "git rebase -i {{.SelectedLocalCommit.Hash}}"
    description: "Interactive rebase from here"
    output: terminal
  - key: "F"
    context: "commits"
    command: "git commit --fixup={{.SelectedLocalCommit.Hash}} && git rebase -i --autosquash {{.SelectedLocalCommit.Hash}}~1"
    description: "Fixup into this commit"
    loadingText: "Fixing up..."
