set -g escape-time 0
set -g mouse on                          # 鼠标支持（滚轮、选中、调整窗格）
set -g history-limit 100000              # 超大历史回滚
set -g display-time 3000                 # 提示信息显示 3 秒
set -g base-index 1                      # 窗口从 1 开始编号（方便按数字快速切换）
set -g pane-base-index 1                 # 窗格也从 1 开始
set -g renumber-windows on               # 关闭窗口后自动重新编号
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-256color:Tc'

set-option -g pane-active-border-style fg=white
set-option -g pane-border-lines double
set-option -g pane-border-status top
set-option -g pane-border-indicators off

set-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection

bind v copy-mode
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# 自定义插件目录
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux/plugins"

# 如果 tpm 不存在则自动安装
if-shell "[ ! -d ${XDG_DATA_HOME}/tmux/plugins/tpm ]" \
    "run-shell 'git clone https://github.com/tmux-plugins/tpm ${XDG_DATA_HOME}/tmux/plugins/tpm'"

# 先定义所有插件
set -g @plugin 'wfxr/tmux-power'
# set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'sainnhe/tmux-fzf'

# 主题设置
set -g @tmux_power_theme 'everforest'
set -g @tmux_power_date_icon           ' '
set -g @tmux_power_time_icon           ' '
# icon 󰫢     
set -g @tmux_power_user_icon           '󰫢'
set -g @tmux_power_session_icon        ' '
set -g @tmux_power_right_arrow_icon    ''
set -g @tmux_power_left_arrow_icon     ''
set -g @tmux_power_upload_speed_icon   '󰕒'
set -g @tmux_power_download_speed_icon '󰇚'

# set -g @tmux_power_show_upload_speed   true
# set -g @tmux_power_show_download_speed true

set -g @tmux_power_prefix_highlight_pos 'R'

# 最后初始化 TPM，这时候才能读到所有插件和配置
run-shell "${XDG_DATA_HOME}/tmux/plugins/tpm/tpm"
set -g @fzf-tmux-options "-p 80%,80%"
unbind s
unbind w
bind-key s run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/session.sh switch"
bind-key w run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/window.sh switch"
#bind-key p run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/pane.sh switch"
