set -g @fzf-tmux-options "-p 80%,80%"
set-environment -g FZF_DEFAULT_OPTS "--height=60% --layout=reverse --border=rounded --margin=0,1 --info=inline-right --prompt='> ' --pointer='▶' --marker='✓' --bind='ctrl-y:accept' --color=fg:#faf9f5,bg:-1,hl:#6a9bcc --color=fg+:#faf9f5,bg+:-1,hl+:#6a9bcc --color=info:#6a9bcc,prompt:#6a9bcc,pointer:#c25848 --color=marker:#788c5d,spinner:#c89b40,header:#6a9bcc"
# 只搜索当前 session 的 window（不加 -a）
set-environment -g TMUX_FZF_WINDOW_FILTER "#{==:1,1}"
set-environment -g TMUX_FZF_PREVIEW 0

unbind s
unbind w

bind-key s run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/session.sh switch"
bind-key w run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/window.sh switch"
