set -g popup-border-lines none

set-environment -g FZF_DEFAULT_OPTS "--height=60% --layout=reverse --border=rounded --margin=0,1 --info=inline-right --prompt='> ' --pointer='▶' --marker='✓' --bind='ctrl-y:accept' --color=fg:#ffffff,bg:-1,hl:#56c2ff --color=fg+:#ffffff,bg+:-1,hl+:#56c2ff --color=info:#56c2ff,prompt:#56c2ff,pointer:#ff5360 --color=marker:#59d499,spinner:#ffc531,header:#56c2ff"

unbind s
unbind w

bind-key s display-popup -E -w 60% -h 60% "target=\$(tmux list-sessions -F '#{session_name}' | fzf --no-height --prompt='session> '); [ -n \"\$target\" ] && tmux switch-client -t \"\$target\""
bind-key w display-popup -E -w 60% -h 60% "target=\$(tmux list-windows -F '#{window_id} #{window_index}: #{window_name}' | fzf --no-height --prompt='window> '); [ -n \"\$target\" ] && tmux select-window -t \"\${target%% *}\""
