set -g @fzf-tmux-options "-p 80%,80%"
set-environment -g FZF_DEFAULT_OPTS "--height=60% --layout=reverse --border=rounded --margin=0,1 --info=inline-right --prompt='> ' --pointer='▶' --marker='✓' --bind='ctrl-y:accept' --color=fg:#ffffff,bg:-1,hl:#56c2ff --color=fg+:#ffffff,bg+:-1,hl+:#56c2ff --color=info:#56c2ff,prompt:#56c2ff,pointer:#ff5360 --color=marker:#59d499,spinner:#ffc531,header:#56c2ff"
# 只搜索当前 session 的 window（不加 -a）
set-environment -g TMUX_FZF_WINDOW_FILTER "#{==:1,1}"
set-environment -g TMUX_FZF_PREVIEW 0

unbind s
unbind w

bind-key s run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/session.sh switch"
bind-key w run-shell -b "${XDG_DATA_HOME}/tmux/plugins/tmux-fzf/scripts/window.sh switch"
