set -g @tmux_power_theme 'everforest'

set -g @tmux_power_right_arrow_icon ''
set -g @tmux_power_left_arrow_icon ''
set -g @tmux_power_left_a ' #{USER}@#h'
set -g @tmux_power_left_b ' #S'
set -g @tmux_power_right_y ' %T'
set -g @tmux_power_right_z ' %F'

set -g @tmux_power_prefix_highlight_pos 'R'


set -g pane-active-border-style fg=white
set -g pane-border-lines double
set -g pane-border-status top
set -g pane-border-indicators off
